server {
    listen 8085;
    server_name localhost;

    root /home/rishi/DevOps-Winter-Arc/Week1-Linux/Task7-GitHub_Production/app;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
